on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test Prusti action
        uses: viperproject/prusti-action@master
        with:
          path: test
